### ISSUE TITLE
error Class 'BigBlueButton\TestCase' not found

### ISSUE THREAD

**Issue by carovidela** [bigbluebutton/bigbluebutton-api-php#132]
Intento ejecutar el archivo BigBlueButtonTest.php, obtuve este error:
Fatal error: Class 'BigBlueButton\TestCase' not found 

No encontre bien como ver el tema de configurar BBB_SECRETy BBB_SERVER_BASE_URLen Xampp? ¿Cómo puedo hacer eso?

De todas formas si quiero usar la libreria no me encuentra la clase como puedo solucionar esto???

Muchas gracias

**Comment by sualko** [comment]
This is an English speaking community, so please use a translator. If you have issues with this api, you maybe want to test our fork with many enhancements and working tests :wink: https://github.com/littleredbutton/bigbluebutton-api-php

**Comment by GhaziTriki** [comment]
Dear @sualko,

I deleted your message. Please don't promote your fork here. The BigBlueButton developers are busy imporving the core product, it does not mean we are not interested into maintaining this library. 

Thank you.

**Comment by sualko** [comment]
All devs from littleredbutton tried to contribute to this project and instead of inviting them, they got mostly ignored. I understand that you are all busy, but especially in such cases you should take any help you get. With working test cases and proper project settings it's a breeze to share responsibility. As a result the workload of the core devs would be reduced. My aim is to help as many people as possible to use bigbluebutton and if someone doesn't get any response within 2 month, I think it's just fair to offer them a great solution.

It would be nice if we could join forces in the future to have only one api.
