### ISSUE TITLE
Sample Of présentation pre-upload

### ISSUE THREAD

**Issue by zikobad** [bigbluebutton/bigbluebutton-api-php#21]
Can you please provide a sample or presentation preupload.
Thanks

**Comment by geezot** [comment]
Hi
If you want to use preupload presentation you just need to do something like this : 
```
$createMeetingParams = new CreateMeetingParameters($meetingId,$meetingName);
[...]
$createMeetingParams->addPresentation('http://url_to_pdf_file.pdf');
```
that's all
and when you start the meeting an xml file is send to server who download the document, you can use repeat addPresentation if you are more than one file to preupload.

**! IMPORTANT TO READ**
But there is a mistake on line 450 in the file CreateMeetingParameters in the method getPresentationsAsXML
there is a urlencode I know this function is use for special caracters but on the server side there is no _**urldecode**_ and you can't upload file because you have a message : Malformed URL in BBB log.
If you remove the _**urlencode**_ everything work fine

regards
fabrice
