### ISSUE TITLE
Use of foreach to iterate over a simple Object in GetMeetingInfoResponse

### ISSUE THREAD

**Issue by lazarait** [bigbluebutton/bigbluebutton-api-php#8]
Hi!
I'am a new user of your project. I think that there is a mistake in the line 69 of the file GetMeetingInfoResponse: `foreach ($this->rawXml->attendees->attendee as $attendeeXml) {`
I guess that you meant `$this->rawXml->attendees` because it is a traversable object.
Besides at the line 68 `$this->attendess = [];`, there is not such property in the class `GetMeetingInfoResponse` and it is never used. I suppose that it is simply a spelling mistake and that you meant `$this->attendees[]`.
Sincerely yours

**Comment by GhaziTriki** [comment]
Thank you for spotting the typo, it has been fixed in https://github.com/bigbluebutton/bigbluebutton-api-php/commit/5b72615dde6b34bf5b6a14fcca696aae7cfd7a3b

However I am not sure about using ```$this->rawXml->attendees``` it makes tests fail the syntax written intially is correct and passes unit tests with success : https://github.com/bigbluebutton/bigbluebutton-api-php/blob/master/tests/Responses/GetMeetingInfoResponseTest.php#L67-L78

You can take a look at a response sample in this file https://github.com/bigbluebutton/bigbluebutton-api-php/blob/master/tests/fixtures/get_meeting_info.xml
