### ISSUE TITLE
Get rid of getenv / Env-Parameters???

### ISSUE THREAD

**Issue by kurzarbeit-einfach** [bigbluebutton/bigbluebutton-api-php#82]
Why would you use "getenv" to configure the BBB-Api class? Why not just passing those two parameters (secret & url) to the constructor?

Using environment variables has several drawbacks - as for example I cannot instanciate multiple objects of your API for managing different BBB Servers inside my application. Likewise, env-variables are easily available for all php scripts running in the same environment.

**Comment by sualko** [comment]
I also don't understand why envs are used and would prefer to pass them directly to the constructur.

**Comment by GhaziTriki** [comment]
The environment variables are use to prevent putting the salt directly in the code.
A previous PR suggested the same thing, please take a look here https://github.com/bigbluebutton/bigbluebutton-api-php/pull/66#issuecomment-616118956

**Comment by sualko** [comment]
As can seen from the other pull request there is a real demand and you can't protect the developer to do bad things. For example they could just use `putenv` to set the env. Also other big libraries like SwiftMail are using the constructor to provide authentication. I don't understand why a backward compatible change without impact for security is not merged.

**Comment by jarmediagmbh** [comment]
+1 sualko! We have forked the bbb api php class into our own repo.

@GhaziTriki Why do you expect developers to not know what they are doing?
Not only is your solution very, very uncommon practice, but:
* It does not improve security as other scripts running in the same environment can easily read this variable.
* It is a real hussle for people using it with some kind of framework in which they are using real central configuration management in php (look at zend framework / laminas / laravel / symfony ... they all provide very good config management).
* Your solution expects all people to only manage exactly ONE server, as your env-variable can only be set to ONE secret. Why is that? What if I wanted to manage multiple?
* Said you wanted to protect devs to put the secret in the code? What if I am managing servers in an application, where the secrets of different servers I want to manage is stored inside the database? Why this would happen? Maybe, because I want to allow the user to dynamically add new servers to the application. Maybe, because my application spawns new cloud servers by itself and thus has to store the generated secrets somewhere in the database for later access.

Sorry, but I cannot follow your arguments.

**Comment by GhaziTriki** [comment]
Hello @jarmediagmbh 

Thank you for your feedback.

When it comes to security, yes we expect that developers are not all the time aware of what they are fully doing when dealing with security, even aware people my do it accidentally.

The choice of not allowing or giving the chance to put the shared secret in the source code is a security choice that you can circle by just extending the class.

Please find below why we are not allowing such thing
https://security.stackexchange.com/questions/191590/why-is-storing-passwords-in-version-control-a-bad-idea

And if you want to check how many passwords were removed from Github just check this link https://github.com/search?q=removed+password&type=Commits

**Comment by SamuelWei** [comment]
Hello @GhaziTriki,

I fully understand your point, but...

In case an attacker has access to the source code to read the cleartext password, they are also capable to read the secret from the .env

The other point I think you want to make is, that implementing this feature could lead to people adding the password as cleartext in the source code and then accidentally publishing it.

On the other hand there might be some use cases, like the project i'm currently working on. I need a feature to dynamically set the api secret and base url, as I store this information for multiple bbb servers in a database. Overwriting the class is a possible, but not the best option.

**Comment by tdjac0bs** [comment]
Hello @SamuelWei A possible workaround for managing multiple servers ( dynamically setting the values ) is calling `putenv` before the usage of the class ( defining the value ) and after the usage of the class ( unseting the value ).

**Comment by sualko** [comment]
It's not more secure to use env, because in such a case this happens: https://github.com/ramezrafla/spreed-bigbluebutton/blob/8acb1aa11c4e19d76274b6b074723dd9a8f33c26/appinfo/app.php#L30-L31

> A possible workaround for managing multiple servers ( dynamically setting the values ) is calling putenv before the usage of the class ( defining the value ) and after the usage of the class ( unseting the value ).

`putenv` is no solution for systems with high security demands, because they disable env. This could also occur on shared hosters. For me env in a php application could also be a security vulnerability, if people but them in there global webserver config, so that every website of them have access to the secret.

Just follow the principles of more wide spread libraries like e.g. swiftmailer. Is this project with 10 contributors really smarter than big ones with thousands?

@SamuelWei and I don't want to hurt anyone, we just want to make this lib better and help to make it easier to use.

**Comment by SamuelWei** [comment]
@sualko i totally agree with you, that's why I created the pull request in the first place

**Comment by jarmediagmbh** [comment]
> When it comes to security, yes we expect that developers are not all the time aware of what they are fully doing when dealing with security, even aware people my do it accidentally.

Well, my guess is, that most of the devs out there won't follow this argumentation.

**But what you wrote is simply - sorry - wrong.** And I cannot believe that you are delivering such misinformation to other devs: Env is BY DESIGN no save place to store CREDENTIALS (!!!), but to provide the application with information that is very specific to the concrete system it runs on ("Am I on dev or prod server?" etc.).

So to sum up: You are encuraging devs that HAVE proper setup and ARE using state-of-the-art config systems to not use it but rather use an insecure (other processes can easily read this), unflexible (only one server) and unusual way of programming. Or, yes, otherwise they can also use a work around. Great advise!

Do not get me wrong, I do not want to offend somebody. We are just "fighting" (verbally of course ;) ) for a great php sdk. :)

**Comment by sualko** [comment]
@jarmediagmbh @SamuelWei I'm getting more and more disappointed with the whole situation. Failing ci tests, even small pr are not merged and so on. Are you interested in creating an own fork? I know that everyone of you, similar to me, are maintaining a fork, but if we join our efforts we could save some time. What do you think? We could create a new org with a fork and than work on merging all pending pr's and such stuff.

**Comment by jarmediagmbh** [comment]
@sualko Yeah, sure. We have detected a few more errors and things that were not implemented yet.
How do we go on?

**Comment by SamuelWei** [comment]
@sualko Sounds like a good idea.

**Comment by sualko** [comment]
:tada: we need a name for our organisation and than I would offer to set everything up, so that we are equal owners of the group. Any ideas for a name? SmallRedButton? :D

**Comment by SamuelWei** [comment]
@sualko Sounds like a good idea. I'm also contributing on this repo https://github.com/joisarjignesh/bigbluebutton to create a good package for laravel that is based on this general php api.
@joisarjignesh Are you interested to move your project to a new org. as well?

**Comment by joisarjignesh** [comment]
@SamuelWei  Yes I would be more than happy to join you all and work for some collective benefit

**Comment by sualko** [comment]
I created a organisation, sent you an invitation and created an issue for further discussions: https://github.com/littleredbutton/bigbluebutton-api-php/issues/4

**Comment by GhaziTriki** [comment]
@sualko We wish you a good luck with your fork initiative. The official API will continue its way with the vision we share. Any new feedback from the community is welcome.

**Comment by sualko** [comment]
> Any new feedback from the community is welcome

The reason for the fork was that community work was not encouraged at this repository and therefore I doubt that there will be any feedback from my side. If you look at our fork you can see what can happen if you motivate people. We already have fixed a lot of issues, added some more functionality and support php 7.4. Feel free to cherry pick those changes.
